AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI-powered RFP Response Agent - EventBridge Rules Template'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    Description: 'Environment name for resource naming'
  
  SamGovDailyDownloadFunctionArn:
    Type: String
    Description: 'ARN of the SAM.gov daily download Lambda function'
  
  SamMergeAndArchiveResultLogsFunctionArn:
    Type: String
    Description: 'ARN of the merge and archive Lambda function'
  
  SamDailyEmailNotificationFunctionArn:
    Type: String
    Description: 'ARN of the daily email notification Lambda function'
  
  BucketPrefix:
    Type: String
    Default: ''
    Description: 'Optional prefix for S3 bucket names to avoid conflicts'

Resources:
  # EventBridge Rules
  SamGovDailyDownloadRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'sam-gov-daily-download-${Environment}'
      Description: 'Trigger SAM.gov daily download Lambda function'
      ScheduleExpression: 'cron(0 6 * * ? *)'  # Daily at 6 AM UTC
      State: DISABLED
      Targets:
        - Arn: !Ref SamGovDailyDownloadFunctionArn
          Id: 'SamGovDailyDownloadTarget'

  SamLambdaEvery5MinSummarizerRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'sam-lambda-every-5min-summarizer-${Environment}'
      Description: 'Trigger merge and archive Lambda function every 5 minutes'
      ScheduleExpression: 'rate(5 minutes)'
      State: ENABLED
      Targets:
        - Arn: !Ref SamMergeAndArchiveResultLogsFunctionArn
          Id: 'SamMergeAndArchiveTarget'

  SamDailyEmailNotificationRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'sam-daily-email-notification-${Environment}'
      Description: 'Trigger daily email notification Lambda function at 10am EST'
      ScheduleExpression: 'cron(0 15 * * ? *)'  # 10am EST = 3pm UTC (15:00)
      State: ENABLED
      Targets:
        - Arn: !Ref SamDailyEmailNotificationFunctionArn
          Id: 'SamDailyEmailNotificationTarget'

  # Lambda Permissions for EventBridge
  SamGovDailyDownloadPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SamGovDailyDownloadFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SamGovDailyDownloadRule.Arn

  SamMergeAndArchivePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SamMergeAndArchiveResultLogsFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SamLambdaEvery5MinSummarizerRule.Arn

  SamDailyEmailNotificationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SamDailyEmailNotificationFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SamDailyEmailNotificationRule.Arn

Outputs:
  SamGovDailyDownloadRuleArn:
    Description: 'ARN of the daily download EventBridge rule'
    Value: !GetAtt SamGovDailyDownloadRule.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SamGovDailyDownloadRule'
  
  SamLambdaEvery5MinSummarizerRuleArn:
    Description: 'ARN of the 5-minute summarizer EventBridge rule'
    Value: !GetAtt SamLambdaEvery5MinSummarizerRule.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SamLambdaEvery5MinSummarizerRule'
  
  SamDailyEmailNotificationRuleArn:
    Description: 'ARN of the daily email notification EventBridge rule'
    Value: !GetAtt SamDailyEmailNotificationRule.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SamDailyEmailNotificationRule'