AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI-powered RFP Response Agent - S3 Event Notifications Template'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    Description: 'Environment name for resource naming'
  
  SqsSamJsonMessagesQueueArn:
    Type: String
    Description: 'ARN of the SQS queue for JSON messages'
  
  BucketPrefix:
    Type: String
    Default: ''
    Description: 'Optional prefix for S3 bucket names to avoid conflicts'

Conditions:
  HasBucketPrefix: !Not [!Equals [!Ref BucketPrefix, '']]

Resources:
  # S3 Bucket Notification Configurations
  # Note: Using custom resources to configure notifications on existing buckets
  
  # SQS Queue Policy to allow S3 to send messages
  SqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    DeletionPolicy: Retain
    Properties:
      Queues:
        - !Sub 'https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${BucketPrefix}-sqs-sam-json-messages-${Environment}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !Ref SqsSamJsonMessagesQueueArn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:::${BucketPrefix}-sam-extracted-json-resources-${Environment}'
  
  # Custom resource Lambda for configuring S3 notifications
  S3NotificationConfiguratorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3NotificationConfiguration
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketNotification
                  - s3:GetBucketNotification
                Resource:
                  - !Sub 'arn:aws:s3:::${BucketPrefix}-sam-data-in-${Environment}'
                  - !Sub 'arn:aws:s3:::${BucketPrefix}-sam-extracted-json-resources-${Environment}'
                  - !Sub 'arn:aws:s3:::${BucketPrefix}-sam-matching-out-sqs-${Environment}'
                  - !Sub 'arn:aws:s3:::${BucketPrefix}-sam-matching-out-runs-${Environment}'

  S3NotificationConfiguratorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${BucketPrefix}-s3-notification-configurator-${Environment}'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt S3NotificationConfiguratorRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import json
          
          s3 = boto3.client('s3')
          
          def handler(event, context):
              import time
              try:
                  print(f"Event: {json.dumps(event)}")
                  
                  if event['RequestType'] == 'Delete':
                      # On delete, remove the notification configuration
                      bucket = event['ResourceProperties']['Bucket']
                      try:
                          s3.put_bucket_notification_configuration(
                              Bucket=bucket,
                              NotificationConfiguration={}
                          )
                      except Exception as e:
                          print(f"Error removing notification: {str(e)}")
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return
                  
                  bucket = event['ResourceProperties']['Bucket']
                  notification_config = json.loads(event['ResourceProperties']['NotificationConfiguration'])
                  
                  # For SQS destinations, add a retry mechanism to allow policy propagation
                  has_sqs = 'QueueConfigurations' in notification_config
                  max_retries = 5 if has_sqs else 1
                  retry_delay = 3
                  
                  last_error = None
                  for attempt in range(max_retries):
                      try:
                          if attempt > 0:
                              print(f"Retry attempt {attempt + 1}/{max_retries} after {retry_delay}s delay...")
                              time.sleep(retry_delay)
                          
                          # Put the notification configuration
                          s3.put_bucket_notification_configuration(
                              Bucket=bucket,
                              NotificationConfiguration=notification_config
                          )
                          
                          cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                              'Message': f'Successfully configured notifications for {bucket}'
                          })
                          return
                      except Exception as e:
                          last_error = e
                          if 'Unable to validate' not in str(e):
                              # If it's not a validation error, don't retry
                              raise
                          print(f"Validation error on attempt {attempt + 1}: {str(e)}")
                  
                  # If we exhausted retries, fail
                  raise last_error
                  
              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {
                      'Message': str(e)
                  })

  # Lambda permission for JSON processor to be invoked by S3
  JsonProcessorS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub '${BucketPrefix}-sam-json-processor-${Environment}'
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${BucketPrefix}-sam-data-in-${Environment}'

  # Lambda permission for user report generator to be invoked by S3
  UserReportS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub '${BucketPrefix}-sam-produce-user-report-${Environment}'
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${BucketPrefix}-sam-matching-out-sqs-${Environment}'

  # Lambda permission for web report generator to be invoked by S3
  WebReportS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub '${BucketPrefix}-sam-produce-web-reports-${Environment}'
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${BucketPrefix}-sam-matching-out-runs-${Environment}'

  # Configure S3 notification for sam-data-in bucket (triggers JSON processor)
  SamDataInBucketNotification:
    Type: Custom::S3Notification
    Properties:
      ServiceToken: !GetAtt S3NotificationConfiguratorFunction.Arn
      Bucket: !Sub '${BucketPrefix}-sam-data-in-${Environment}'
      NotificationConfiguration: !Sub |
        {
          "LambdaFunctionConfigurations": [
            {
              "LambdaFunctionArn": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${BucketPrefix}-sam-json-processor-${Environment}",
              "Events": ["s3:ObjectCreated:*"]
            }
          ]
        }
    DependsOn: JsonProcessorS3Permission

  # Configure S3 notification for sam-extracted-json-resources bucket (triggers SQS)
  SamExtractedJsonResourcesBucketNotification:
    Type: Custom::S3Notification
    Properties:
      ServiceToken: !GetAtt S3NotificationConfiguratorFunction.Arn
      Bucket: !Sub '${BucketPrefix}-sam-extracted-json-resources-${Environment}'
      NotificationConfiguration: !Sub
        - |
          {
            "QueueConfigurations": [
              {
                "QueueArn": "${QueueArn}",
                "Events": ["s3:ObjectCreated:*"]
              }
            ]
          }
        - QueueArn: !Ref SqsSamJsonMessagesQueueArn
    DependsOn: SqsQueuePolicy

  # Configure S3 notification for sam-matching-out-sqs bucket (triggers user report)
  SamMatchingOutSqsBucketNotification:
    Type: Custom::S3Notification
    Properties:
      ServiceToken: !GetAtt S3NotificationConfiguratorFunction.Arn
      Bucket: !Sub '${BucketPrefix}-sam-matching-out-sqs-${Environment}'
      NotificationConfiguration: !Sub |
        {
          "LambdaFunctionConfigurations": [
            {
              "LambdaFunctionArn": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${BucketPrefix}-sam-produce-user-report-${Environment}",
              "Events": ["s3:ObjectCreated:*"],
              "Filter": {
                "Key": {
                  "FilterRules": [
                    {
                      "Name": "suffix",
                      "Value": ".json"
                    }
                  ]
                }
              }
            }
          ]
        }
    DependsOn: UserReportS3Permission

  # Configure S3 notification for sam-matching-out-runs bucket (triggers web report)
  SamMatchingOutRunsBucketNotification:
    Type: Custom::S3Notification
    Properties:
      ServiceToken: !GetAtt S3NotificationConfiguratorFunction.Arn
      Bucket: !Sub '${BucketPrefix}-sam-matching-out-runs-${Environment}'
      NotificationConfiguration: !Sub |
        {
          "LambdaFunctionConfigurations": [
            {
              "LambdaFunctionArn": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${BucketPrefix}-sam-produce-web-reports-${Environment}",
              "Events": ["s3:ObjectCreated:*"],
              "Filter": {
                "Key": {
                  "FilterRules": [
                    {
                      "Name": "prefix",
                      "Value": "runs/2"
                    }
                  ]
                }
              }
            }
          ]
        }
    DependsOn: WebReportS3Permission

Outputs:
  S3NotificationConfiguratorFunctionArn:
    Description: 'ARN of the S3 notification configurator Lambda function'
    Value: !GetAtt S3NotificationConfiguratorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-S3NotificationConfiguratorFunction'
  
  NotificationsConfigured:
    Description: 'S3 event notifications configured'
    Value: 'true'