AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AI-powered RFP Response Agent infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  SAMAPIKey:
    Type: String
    NoEcho: true
    Description: API key for SAM.gov access

Globals:
  Function:
    Runtime: python3.11
    Timeout: 300
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: INFO

Resources:
  # SQS Dead Letter Queue
  SamJsonMessagesDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-sqs-sam-json-messages-dlq"
      MessageRetentionPeriod: 1209600  # 14 days
      VisibilityTimeout: 60
      KmsMasterKeyId: alias/aws/sqs
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: DeadLetterQueue

  # Main SQS Queue for SAM JSON messages
  SamJsonMessagesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-sqs-sam-json-messages"
      VisibilityTimeout: 300  # 5 minutes (matches Lambda timeout)
      MessageRetentionPeriod: 1209600  # 14 days
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      KmsMasterKeyId: alias/aws/sqs
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SamJsonMessagesDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: OpportunityProcessing

  # S3 Bucket for extracted JSON resources (triggers SQS messages)
  SamExtractedJsonResourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-sam-extracted-json-resources"
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
          - Id: DeleteAfter90Days
            Status: Enabled
            ExpirationInDays: 90
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt SamJsonMessagesQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .json
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: ProcessedOpportunities

  # SQS Queue Policy to allow S3 to send messages
  SamJsonMessagesQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SamJsonMessagesQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt SamJsonMessagesQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt SamExtractedJsonResourcesBucket.Arn

  # S3 Bucket for company information (Knowledge Base data source)
  SamCompanyInfoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-sam-company-info"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: CompanyInformation

  # OpenSearch Serverless Collection for Bedrock Knowledge Base vector store
  BedrockKnowledgeBaseCollection:
    Type: AWS::OpenSearchServerless::Collection
    Properties:
      Name: !Sub "${Environment}-company-info-kb-collection"
      Type: VECTORSEARCH
      Description: Vector store for Company Information Knowledge Base
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: BedrockKnowledgeBase

  # OpenSearch Serverless Security Policy for the collection
  BedrockKnowledgeBaseSecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub "${Environment}-company-info-kb-security-policy"
      Type: encryption
      Policy: !Sub |
        {
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": ["collection/${Environment}-company-info-kb-collection"]
            }
          ],
          "AWSOwnedKey": true
        }

  # OpenSearch Serverless Network Policy
  BedrockKnowledgeBaseNetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub "${Environment}-company-info-kb-network-policy"
      Type: network
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/${Environment}-company-info-kb-collection"],
                "AllowFromPublic": true
              },
              {
                "ResourceType": "dashboard",
                "Resource": ["collection/${Environment}-company-info-kb-collection"],
                "AllowFromPublic": true
              }
            ]
          }
        ]

  # IAM Role for Bedrock Knowledge Base
  BedrockKnowledgeBaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-BedrockKnowledgeBaseRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
      Policies:
        - PolicyName: S3DataSourceAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${SamCompanyInfoBucket}/*"
                  - !GetAtt SamCompanyInfoBucket.Arn
        - PolicyName: OpenSearchServerlessAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - aoss:APIAccessAll
                Resource: !Sub "arn:aws:aoss:${AWS::Region}:${AWS::AccountId}:collection/${Environment}-company-info-kb-collection"

  # OpenSearch Serverless Data Access Policy
  BedrockKnowledgeBaseDataAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: !Sub "${Environment}-company-info-kb-data-access-policy"
      Type: data
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/${Environment}-company-info-kb-collection"],
                "Permission": [
                  "aoss:CreateCollectionItems",
                  "aoss:DeleteCollectionItems",
                  "aoss:UpdateCollectionItems",
                  "aoss:DescribeCollectionItems"
                ]
              },
              {
                "ResourceType": "index",
                "Resource": ["index/${Environment}-company-info-kb-collection/*"],
                "Permission": [
                  "aoss:CreateIndex",
                  "aoss:DeleteIndex",
                  "aoss:UpdateIndex",
                  "aoss:DescribeIndex",
                  "aoss:ReadDocument",
                  "aoss:WriteDocument"
                ]
              }
            ],
            "Principal": ["${BedrockKnowledgeBaseRole.Arn}"]
          }
        ]

  # Bedrock Knowledge Base
  CompanyInformationKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    DependsOn: 
      - BedrockKnowledgeBaseCollection
      - BedrockKnowledgeBaseDataAccessPolicy
    Properties:
      Name: !Sub "${Environment}-Company-Information-KB"
      Description: Knowledge Base containing company information for opportunity matching
      RoleArn: !GetAtt BedrockKnowledgeBaseRole.Arn
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v1"
      StorageConfiguration:
        Type: OPENSEARCH_SERVERLESS
        OpensearchServerlessConfiguration:
          CollectionArn: !GetAtt BedrockKnowledgeBaseCollection.CollectionArn
          VectorIndexName: company-info-index
          FieldMapping:
            VectorField: vector
            TextField: text
            MetadataField: metadata
      Tags:
        Environment: !Ref Environment
        Purpose: CompanyInformation

  # Bedrock Knowledge Base Data Source
  CompanyInformationDataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      Name: !Sub "${Environment}-Company-Info-S3-DataSource"
      Description: S3 data source for company information
      KnowledgeBaseId: !Ref CompanyInformationKnowledgeBase
      DataSourceConfiguration:
        Type: S3
        S3Configuration:
          BucketArn: !GetAtt SamCompanyInfoBucket.Arn
          InclusionPrefixes: []
      VectorIngestionConfiguration:
        ChunkingConfiguration:
          ChunkingStrategy: FIXED_SIZE
          FixedSizeChunkingConfiguration:
            MaxTokens: 300
            OverlapPercentage: 20

  # S3 Buckets will be defined here
  # Lambda Functions will be defined here
  # IAM Roles will be defined here
  # EventBridge Rules will be defined here

Outputs:
  Environment:
    Description: Environment name
    Value: !Ref Environment
  
  SamJsonMessagesQueueUrl:
    Description: URL of the SQS queue for SAM JSON messages
    Value: !Ref SamJsonMessagesQueue
    Export:
      Name: !Sub "${Environment}-SamJsonMessagesQueueUrl"
  
  SamJsonMessagesQueueArn:
    Description: ARN of the SQS queue for SAM JSON messages
    Value: !GetAtt SamJsonMessagesQueue.Arn
    Export:
      Name: !Sub "${Environment}-SamJsonMessagesQueueArn"
  
  SamJsonMessagesDLQUrl:
    Description: URL of the dead letter queue
    Value: !Ref SamJsonMessagesDLQ
    Export:
      Name: !Sub "${Environment}-SamJsonMessagesDLQUrl"
  
  SamExtractedJsonResourcesBucketName:
    Description: Name of the S3 bucket for extracted JSON resources
    Value: !Ref SamExtractedJsonResourcesBucket
    Export:
      Name: !Sub "${Environment}-SamExtractedJsonResourcesBucketName"
  
  SamCompanyInfoBucketName:
    Description: Name of the S3 bucket for company information
    Value: !Ref SamCompanyInfoBucket
    Export:
      Name: !Sub "${Environment}-SamCompanyInfoBucketName"
  
  CompanyInformationKnowledgeBaseId:
    Description: ID of the Bedrock Knowledge Base for company information
    Value: !Ref CompanyInformationKnowledgeBase
    Export:
      Name: !Sub "${Environment}-CompanyInformationKnowledgeBaseId"
  
  CompanyInformationDataSourceId:
    Description: ID of the Bedrock Knowledge Base data source
    Value: !Ref CompanyInformationDataSource
    Export:
      Name: !Sub "${Environment}-CompanyInformationDataSourceId"