# Deploy API Gateway Stack for RFP Response Agent
# This script deploys the API Gateway and Lambda backend

param(
    [string]$Environment = "dev",
    [string]$Region = "us-east-1",
    [string]$ProjectPrefix = "l3harris-qhan"
)

$ErrorActionPreference = "Stop"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "RFP Response Agent - API Gateway Deployment" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Configuration
$StackName = "$ProjectPrefix-api-gateway-$Environment"
$TemplateFile = "$PSScriptRoot\..\infrastructure\api-gateway-stack.yaml"
$S3Bucket = "$ProjectPrefix-sam-deployments-$Environment"

Write-Host "Configuration:" -ForegroundColor Yellow
Write-Host "  Stack Name: $StackName" -ForegroundColor White
Write-Host "  Environment: $Environment" -ForegroundColor White
Write-Host "  Region: $Region" -ForegroundColor White
Write-Host "  Template: $TemplateFile" -ForegroundColor White
Write-Host ""

# Step 1: Check if AWS CLI is configured
Write-Host "Step 1: Checking AWS CLI configuration..." -ForegroundColor Cyan
$AccountId = aws sts get-caller-identity --query Account --output text 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] AWS CLI not configured or no credentials found" -ForegroundColor Red
    Write-Host "  Please run: aws configure" -ForegroundColor Yellow
    exit 1
}
Write-Host "[OK] AWS Account: $AccountId" -ForegroundColor Green
Write-Host ""

# Step 2: Create S3 bucket for SAM deployments if it doesn't exist
Write-Host "Step 2: Ensuring deployment bucket exists..." -ForegroundColor Cyan
$CreateResult = aws s3 mb "s3://$S3Bucket" --region $Region 2>&1 | Out-String
if ($CreateResult -like "*BucketAlreadyOwnedByYou*" -or $CreateResult -like "*make_bucket*") {
    Write-Host "[OK] Bucket ready: $S3Bucket" -ForegroundColor Green
} elseif ($LASTEXITCODE -eq 0) {
    Write-Host "[OK] Bucket created: $S3Bucket" -ForegroundColor Green
} else {
    Write-Host "[ERROR] Failed to ensure bucket exists" -ForegroundColor Red
    Write-Host $CreateResult -ForegroundColor Gray
    exit 1
}
Write-Host ""

# Step 3: Package the Lambda code
Write-Host "Step 3: Packaging Lambda code..." -ForegroundColor Cyan
$PackagedTemplate = "$PSScriptRoot\..\infrastructure\api-gateway-stack-packaged.yaml"

Write-Host "  Running SAM package..." -ForegroundColor Yellow
sam package `
    --template-file $TemplateFile `
    --s3-bucket $S3Bucket `
    --output-template-file $PackagedTemplate `
    --region $Region

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] SAM package failed" -ForegroundColor Red
    exit 1
}
Write-Host "[OK] Package complete" -ForegroundColor Green
Write-Host ""

# Step 4: Deploy the stack
Write-Host "Step 4: Deploying CloudFormation stack..." -ForegroundColor Cyan
Write-Host "  This may take 2-3 minutes..." -ForegroundColor Yellow

sam deploy `
    --template-file $PackagedTemplate `
    --stack-name $StackName `
    --capabilities CAPABILITY_IAM `
    --parameter-overrides `
        Environment=$Environment `
        ProjectPrefix=$ProjectPrefix `
    --region $Region `
    --no-fail-on-empty-changeset

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Deployment failed" -ForegroundColor Red
    exit 1
}
Write-Host "[OK] Deployment complete" -ForegroundColor Green
Write-Host ""

# Step 5: Get the API endpoint
Write-Host "Step 5: Retrieving API Gateway endpoint..." -ForegroundColor Cyan
$ApiEndpoint = aws cloudformation describe-stacks `
    --stack-name $StackName `
    --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" `
    --output text `
    --region $Region

if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($ApiEndpoint)) {
    Write-Host "[ERROR] Failed to retrieve API endpoint" -ForegroundColor Red
    exit 1
}

Write-Host "[OK] API Endpoint: $ApiEndpoint" -ForegroundColor Green
Write-Host ""

# Step 6: Test the API
Write-Host "Step 6: Testing API health endpoint..." -ForegroundColor Cyan
try {
    $Response = Invoke-RestMethod -Uri "$ApiEndpoint/health" -Method Get -TimeoutSec 10
    Write-Host "[OK] API is responding:" -ForegroundColor Green
    Write-Host ($Response | ConvertTo-Json) -ForegroundColor White
} catch {
    Write-Host "[WARN] API endpoint created but health check failed (this is normal on first deploy)" -ForegroundColor Yellow
    Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Gray
}
Write-Host ""

# Step 7: Update UI environment file
Write-Host "Step 7: Updating UI environment configuration..." -ForegroundColor Cyan
$EnvFile = "$PSScriptRoot\..\ui\.env"
$EnvContent = @"
# API Gateway Endpoint (Auto-generated by deploy-api-gateway.ps1)
VITE_API_BASE_URL=$ApiEndpoint

# AWS Region
VITE_AWS_REGION=$Region

# Environment
VITE_ENVIRONMENT=$Environment

# Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@

$EnvContent | Out-File -FilePath $EnvFile -Encoding UTF8 -Force
Write-Host "[OK] Created $EnvFile" -ForegroundColor Green
Write-Host ""

# Summary
Write-Host "========================================" -ForegroundColor Green
Write-Host "Deployment Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "API Gateway Endpoint:" -ForegroundColor Cyan
Write-Host "  $ApiEndpoint" -ForegroundColor White
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "  1. Restart your UI dev server:" -ForegroundColor White
Write-Host "     cd ui" -ForegroundColor Gray
Write-Host "     npm run dev" -ForegroundColor Gray
Write-Host ""
Write-Host "  2. Open browser to http://localhost:3001" -ForegroundColor White
Write-Host ""
Write-Host "  3. Test workflow by clicking 'Run Workflow' in the UI" -ForegroundColor White
Write-Host ""
Write-Host "Available Endpoints:" -ForegroundColor Cyan
Write-Host "  GET  $ApiEndpoint/health" -ForegroundColor Gray
Write-Host "  GET  $ApiEndpoint/dashboard/metrics" -ForegroundColor Gray
Write-Host "  GET  $ApiEndpoint/opportunities" -ForegroundColor Gray
Write-Host "  POST $ApiEndpoint/workflow/trigger" -ForegroundColor Gray
Write-Host "  GET  $ApiEndpoint/matches" -ForegroundColor Gray
Write-Host "  GET  $ApiEndpoint/reports" -ForegroundColor Gray
Write-Host ""
Write-Host "Stack Information:" -ForegroundColor Cyan
Write-Host "  Stack Name: $StackName" -ForegroundColor White
Write-Host "  Region: $Region" -ForegroundColor White
Write-Host "  Status: $(aws cloudformation describe-stacks --stack-name $StackName --query 'Stacks[0].StackStatus' --output text --region $Region)" -ForegroundColor White
Write-Host ""
