AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'API Gateway + Lambda Backend for RFP Response Agent UI'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'
  
  ProjectPrefix:
    Type: String
  # Default removed; must be provided via parameter or environment
    Description: 'Prefix for resource naming to match existing Lambdas'

Resources:
  # API Gateway REST API
  RfpApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${ProjectPrefix}-rfp-api-${Environment}'
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      Auth:
        DefaultAuthorizer: NONE
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true

  # API Backend Lambda Function
  ApiBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectPrefix}-sam-api-backend-${Environment}'
      Description: 'API Gateway handler for RFP UI backend'
      CodeUri: ../src/lambdas/api-backend/
      Handler: handler.lambda_handler
      Runtime: python3.11
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          PROJECT_PREFIX: !Ref ProjectPrefix
          BUCKET_PREFIX: !Ref ProjectPrefix
          DOWNLOAD_LAMBDA: !Sub '${ProjectPrefix}-sam-gov-daily-download-${Environment}'
          PROCESSOR_LAMBDA: !Sub '${ProjectPrefix}-sam-json-processor-${Environment}'
          MATCH_LAMBDA: !Sub '${ProjectPrefix}-sam-sqs-generate-match-reports-${Environment}'
          WEB_REPORT_LAMBDA: !Sub '${ProjectPrefix}-sam-produce-web-reports-${Environment}'
          USER_REPORT_LAMBDA: !Sub '${ProjectPrefix}-sam-produce-user-report-${Environment}'
          EMAIL_LAMBDA: !Sub '${ProjectPrefix}-sam-daily-email-notification-${Environment}'
          ARCHIVE_LAMBDA: !Sub '${ProjectPrefix}-sam-merge-and-archive-result-logs-${Environment}'
      Policies:
        - Version: '2012-10-17'
          Statement:
            # Allow invoking other Lambda functions
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ProjectPrefix}-sam-*'
            # Allow DynamoDB access (for future use)
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*'
            # Allow S3 access
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - !Sub 'arn:aws:s3:::${ProjectPrefix}-*'
                - !Sub 'arn:aws:s3:::${ProjectPrefix}-*/*'
                - 'arn:aws:s3:::sam-*'
                - 'arn:aws:s3:::sam-*/*'
            # Allow CloudWatch Logs
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      Events:
        # Dashboard endpoints
        GetDashboardMetrics:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /dashboard/metrics
            Method: GET
        
        GetDashboardActivity:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /dashboard/activity
            Method: GET
        
        # Opportunities endpoints
        GetOpportunities:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /opportunities
            Method: GET
        
        GetOpportunityById:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /opportunities/{id}
            Method: GET
        
        # Matches endpoints
        GetMatches:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /matches
            Method: GET
        
        GetMatchById:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /matches/{id}
            Method: GET
        
        # Workflow endpoints
        TriggerWorkflow:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /workflow/trigger
            Method: POST
        
        GetWorkflowStatus:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /workflow/status/{executionId}
            Method: GET
        
        GetWorkflowHistory:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /workflow/history
            Method: GET
        
        # Reports endpoints
        GetReports:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /reports
            Method: GET
        
        GetReportById:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /reports/{id}
            Method: GET
        
        DownloadReport:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /reports/{id}/download
            Method: GET
        
        # Settings endpoints
        GetSettings:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /settings
            Method: GET
        
        UpdateSettings:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /settings
            Method: PUT
        
        # Health check
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref RfpApiGateway
            Path: /health
            Method: GET

Outputs:
  ApiEndpoint:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${RfpApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${ProjectPrefix}-api-endpoint-${Environment}'
  
  ApiFunctionArn:
    Description: 'API Backend Lambda Function ARN'
    Value: !GetAtt ApiBackendFunction.Arn
    Export:
      Name: !Sub '${ProjectPrefix}-api-function-arn-${Environment}'
  
  ApiId:
    Description: 'API Gateway ID'
    Value: !Ref RfpApiGateway
    Export:
      Name: !Sub '${ProjectPrefix}-api-id-${Environment}'
