"""
Template management for user report generation.
Handles text and Word document templates for match results.
"""

from typing import Dict, Any, Optional
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

class TemplateManager:
    """Manages templates for text and Word document generation."""
    
    def __init__(self):
        """Initialize template manager with predefined templates."""
        self.text_templates = self._load_text_templates()
        self.email_templates = self._load_email_templates()
    
    def _load_text_templates(self) -> Dict[str, str]:
        """Load text report templates."""
        return {
            'header': """
=== SAM OPPORTUNITY MATCH REPORT ===
Generated: {timestamp}
Solicitation ID: {solicitation_id}
Match Score: {match_score:.2f}
Match Status: {match_status}

""",
            'opportunity_summary': """
OPPORTUNITY SUMMARY
==================
Title: {title}
Value: {value}
Deadline: {deadline}
NAICS Codes: {naics_codes}

""",
            'match_analysis': """
MATCH ANALYSIS
==============
Match Score: {match_score:.2f} ({match_percentage:.1f}%)
Match Status: {match_status}

Rationale:
{rationale}

""",
            'required_skills': """
OPPORTUNITY REQUIRED SKILLS
===========================
{required_skills}

""",
            'company_skills': """
COMPANY MATCHING SKILLS
=======================
{company_skills}

""",
            'past_performance': """
RELEVANT PAST PERFORMANCE
=========================
{past_performance}

""",
            'citations': """
SUPPORTING CITATIONS
====================
{citations}

""",
            'footer': """
=== END OF REPORT ===
Report generated by AI RFP Response Agent
Company: {company_name}
Contact: {company_contact}
"""
        }
    
    def _load_email_templates(self) -> Dict[str, str]:
        """Load email templates for POC outreach."""
        return {
            'subject': "Expression of Interest - {title} ({solicitation_id})",
            'body': """Dear {poc_name},

I hope this email finds you well. I am writing to express {company_name}'s strong interest in the opportunity titled "{title}" (Solicitation ID: {solicitation_id}).

After reviewing the requirements, we believe our company is well-positioned to deliver exceptional results for this project. Our analysis indicates a strong alignment between your needs and our capabilities, with a match score of {match_score:.1f}%.

KEY QUALIFICATIONS:
{key_qualifications}

RELEVANT EXPERIENCE:
{relevant_experience}

We would welcome the opportunity to discuss how our expertise can contribute to the success of this project. Please let me know if you would like to schedule a brief call to explore our capabilities further.

Thank you for your time and consideration. I look forward to hearing from you.

Best regards,

{contact_name}
{company_name}
{company_contact}

---
This email was generated based on automated analysis of the opportunity requirements against our company capabilities. For detailed analysis, please see the attached comprehensive report.
""",
            'no_match_body': """Dear {poc_name},

Thank you for posting the opportunity titled "{title}" (Solicitation ID: {solicitation_id}).

After careful review of the requirements, we have determined that this opportunity may not be the best fit for our current capabilities and focus areas. However, we appreciate being informed of this opportunity and would be interested in future opportunities that align more closely with our expertise.

If you have other upcoming projects in the following areas, we would be very interested in learning more:
{company_focus_areas}

Thank you for your time, and we look forward to potential collaboration on future opportunities.

Best regards,

{contact_name}
{company_name}
{company_contact}
"""
        }
    
    def get_text_template(self, template_name: str) -> str:
        """
        Get a text template by name.
        
        Args:
            template_name: Name of the template
            
        Returns:
            str: Template string
        """
        template = self.text_templates.get(template_name)
        if not template:
            logger.warning(f"Template '{template_name}' not found")
            return ""
        return template
    
    def get_email_template(self, template_name: str) -> str:
        """
        Get an email template by name.
        
        Args:
            template_name: Name of the template
            
        Returns:
            str: Template string
        """
        template = self.email_templates.get(template_name)
        if not template:
            logger.warning(f"Email template '{template_name}' not found")
            return ""
        return template
    
    def format_template(self, template: str, data: Dict[str, Any]) -> str:
        """
        Format a template with provided data.
        
        Args:
            template: Template string with placeholders
            data: Data dictionary for template formatting
            
        Returns:
            str: Formatted template
        """
        try:
            return template.format(**data)
        except KeyError as e:
            logger.warning(f"Missing template data key: {e}")
            # Return template with unfilled placeholders rather than failing
            return template
        except Exception as e:
            logger.error(f"Template formatting error: {e}")
            return template
    
    def prepare_template_data(self, match_data: Dict[str, Any], 
                            company_info: Dict[str, str]) -> Dict[str, Any]:
        """
        Prepare data dictionary for template formatting.
        
        Args:
            match_data: Match result data from AI processing
            company_info: Company information
            
        Returns:
            dict: Formatted data for templates
        """
        # Format timestamp
        timestamp = match_data.get('timestamp', datetime.now().isoformat())
        if 'T' in timestamp:
            # Convert ISO format to readable format
            try:
                dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
                timestamp = dt.strftime('%Y-%m-%d %H:%M:%S UTC')
            except:
                timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')
        
        # Format match status
        match_score = match_data.get('score', 0.0)
        match_threshold = 0.7  # Default threshold
        is_match = match_score >= match_threshold
        match_status = "MATCH" if is_match else "NO MATCH"
        match_percentage = match_score * 100
        
        # Format lists as strings
        required_skills = self._format_list(match_data.get('opportunity_required_skills', []))
        company_skills = self._format_list(match_data.get('company_skills', []))
        past_performance = self._format_list(match_data.get('past_performance', []))
        
        # Format citations
        citations = self._format_citations(match_data.get('citations', []))
        
        # Extract POC information
        poc_name = match_data.get('pointOfContact.fullName', 'Contracting Officer')
        if not poc_name or poc_name == '':
            poc_name = 'Contracting Officer'
        
        # Prepare template data
        template_data = {
            'timestamp': timestamp,
            'solicitation_id': match_data.get('solicitationNumber', match_data.get('solicitation_id', 'Unknown')),
            'match_score': match_score,
            'match_percentage': match_percentage,
            'match_status': match_status,
            'title': match_data.get('title', 'Unknown Title'),
            'value': 'Not specified',  # This field is not in the current match data structure
            'deadline': match_data.get('responseDeadLine', 'Not specified'),
            'naics_codes': 'Not specified',  # This field is not in the current match data structure
            'rationale': match_data.get('rationale', 'No rationale provided'),
            'required_skills': required_skills,
            'company_skills': company_skills,
            'past_performance': past_performance,
            'citations': citations,
            'company_name': company_info.get('name', 'Your Company'),
            'company_contact': company_info.get('contact', 'contact@yourcompany.com'),
            'contact_name': company_info.get('contact_name', 'Business Development Team'),
            'poc_name': poc_name,
            'key_qualifications': self._extract_key_qualifications(match_data),
            'relevant_experience': self._extract_relevant_experience(match_data),
            'company_focus_areas': self._extract_company_focus_areas(match_data)
        }
        
        return template_data
    
    def _format_list(self, items: list) -> str:
        """Format a list as a bulleted string."""
        if not items:
            return "None specified"
        return "\n".join(f"• {item}" for item in items)
    
    def _format_citations(self, citations: list) -> str:
        """Format citations as a readable string."""
        if not citations:
            return "No citations available"
        
        formatted_citations = []
        for i, citation in enumerate(citations, 1):
            doc_title = citation.get('document_title', 'Unknown Document')
            section = citation.get('section_or_page', 'Unknown Section')
            excerpt = citation.get('excerpt', 'No excerpt available')
            
            formatted_citation = f"{i}. {doc_title} - {section}\n   \"{excerpt}\""
            formatted_citations.append(formatted_citation)
        
        return "\n\n".join(formatted_citations)
    
    def _extract_key_qualifications(self, match_data: Dict[str, Any]) -> str:
        """Extract key qualifications for email template."""
        company_skills = match_data.get('company_skills', [])
        if not company_skills:
            return "• Comprehensive capabilities aligned with your requirements"
        
        # Take top 3-4 skills for email brevity
        top_skills = company_skills[:4]
        return "\n".join(f"• {skill}" for skill in top_skills)
    
    def _extract_relevant_experience(self, match_data: Dict[str, Any]) -> str:
        """Extract relevant experience for email template."""
        past_performance = match_data.get('past_performance', [])
        if not past_performance:
            return "• Proven track record in similar government contracting projects"
        
        # Take top 2-3 experiences for email brevity
        top_experience = past_performance[:3]
        return "\n".join(f"• {exp}" for exp in top_experience)
    
    def _extract_company_focus_areas(self, match_data: Dict[str, Any]) -> str:
        """Extract company focus areas for no-match email template."""
        company_skills = match_data.get('company_skills', [])
        if not company_skills:
            return "• Technology solutions and consulting services"
        
        # Take top 3 focus areas
        focus_areas = company_skills[:3]
        return "\n".join(f"• {area}" for area in focus_areas)